/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check for scripts: 200 when the database is reachable, 503 otherwise.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Status
         * @description Setup checklist data: database, worker, Claude CLI, API keys, and network access.
         *
         *     Claude's version and sign-in are cached for a few minutes; `recheck=true` asks again now.
         */
        get: operations["system_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List People */
        get: operations["list_people"];
        put?: never;
        /** Create Person */
        post: operations["create_person"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Person */
        put: operations["update_person"];
        post?: never;
        /** Delete Person */
        delete: operations["delete_person"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips"];
        put?: never;
        /** Create Trip */
        post: operations["create_trip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["get_trip"];
        /** Update Trip */
        put: operations["update_trip"];
        post?: never;
        /** Delete Trip */
        delete: operations["delete_trip"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/refresh-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Destination Info
         * @description Fetch Wikipedia summaries and photos again for destinations that don't have them.
         */
        post: operations["refresh_destination_info"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Routes */
        get: operations["list_routes"];
        put?: never;
        /** Create Route */
        post: operations["create_route"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{route_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Route */
        put: operations["update_route"];
        post?: never;
        /** Delete Route */
        delete: operations["delete_route"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/flights/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Prices
         * @description Check prices now (all routes, or the ones listed).
         */
        post: operations["refresh_prices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/flights/best": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Best Options
         * @description Latest price per itinerary, cheapest first.
         */
        get: operations["best_options"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/flights/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Route Summaries */
        get: operations["route_summaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{route_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Route History */
        get: operations["route_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{route_id}/date-grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Date Grid */
        get: operations["date_grid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flight-quotes/{quote_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Quote
         * @description Hide a fare, or confirm one flagged as suspect.
         */
        patch: operations["update_quote"];
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description Log lines after `after_seq`, for polling while a run is in progress.
         */
        get: operations["run_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/outputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Outputs
         * @description What the run saved (prices and notes) and what was rejected, with the reasons.
         */
        get: operations["run_outputs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Routines */
        get: operations["list_routines"];
        put?: never;
        /** Add Routine */
        post: operations["add_routine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/routines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trip Routines */
        get: operations["trip_routines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routines/{routine_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Routine Detail */
        get: operations["get_routine_detail"];
        put?: never;
        post?: never;
        /** Remove Routine */
        delete: operations["remove_routine"];
        options?: never;
        head?: never;
        /** Update Routine */
        patch: operations["update_routine"];
        trace?: never;
    };
    "/api/v1/routines/{routine_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Routine Now
         * @description Queue a run now. If one is already waiting to start, that run is returned instead.
         */
        post: operations["run_routine_now"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trip Notes
         * @description Findings saved by research agents, newest first.
         */
        get: operations["trip_notes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Note */
        delete: operations["delete_note"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/serpapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serpapi Usage
         * @description Live Google Flights searches used and left under the monthly cap.
         */
        get: operations["serpapi_usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Destination Suggestions */
        get: operations["destination_suggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/airports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Airports */
        get: operations["airports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/airports/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Airports Nearby
         * @description Airports near a destination, for suggesting where to fly.
         */
        get: operations["airports_nearby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings"];
        /** Update Settings */
        put: operations["update_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/v1/runs/{run_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Context
         * @description The task: trip, routes with ids and date rules, cheapest known prices, and the rules.
         */
        get: operations["run_context"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/v1/airports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup Airports */
        get: operations["lookup_airports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/v1/runs/{run_id}/flight-quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Flight Quotes
         * @description Up to 50 prices. Each is accepted, rejected with reasons, or reported as a duplicate.
         */
        post: operations["submit_flight_quotes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/v1/runs/{run_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Note */
        post: operations["add_note"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/v1/runs/{run_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Run */
        post: operations["finish_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptedItem */
        AcceptedItem: {
            /** Index */
            index: number;
            /** Id */
            id: number;
            /** Flags */
            flags: string[];
        };
        /**
         * AccessInfo
         * @description Whether other devices on the home network can open the app, and at which addresses.
         */
        AccessInfo: {
            /** Other Devices */
            other_devices: boolean;
            /** Passcode Configured */
            passcode_configured: boolean;
            /** Port */
            port: number;
            /** Urls */
            urls: string[];
        };
        /** AgentAck */
        AgentAck: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
        };
        /** AirportOut */
        AirportOut: {
            /** Iata */
            iata: string;
            /** Name */
            name: string;
            /** City */
            city: string | null;
            /** Country Code */
            country_code: string;
            /** Kind */
            kind: string;
        };
        /** AppSettingsIn */
        AppSettingsIn: {
            /** Home Currency */
            home_currency: string;
        };
        /** AppSettingsOut */
        AppSettingsOut: {
            /** Home Currency */
            home_currency: string;
        };
        /** ClaudeCliStatus */
        ClaudeCliStatus: {
            /** Found */
            found: boolean;
            /** Path */
            path?: string | null;
            /** Version */
            version?: string | null;
            /** Signed In */
            signed_in?: boolean | null;
            /** Auth Method */
            auth_method?: string | null;
        };
        /** ContextRoute */
        ContextRoute: {
            /** Id */
            id: number;
            /** Label */
            label: string | null;
            /** Origins */
            origins: string[];
            /** Destinations */
            destinations: string[];
            /** Trip Type */
            trip_type: string;
            /**
             * Depart From
             * Format: date
             */
            depart_from: string;
            /**
             * Depart To
             * Format: date
             */
            depart_to: string;
            /** Nights */
            nights: number[] | null;
            /** Return Window */
            return_window: string[] | null;
            /** Passengers */
            passengers: number;
            /** Adults */
            adults: number;
            /** Children */
            children: number;
            /** Cabin */
            cabin: string;
            /** Max Stops */
            max_stops: number | null;
            /** Cheapest Known */
            cheapest_known: {
                [key: string]: unknown;
            } | null;
        };
        /** DateGridCell */
        DateGridCell: {
            /**
             * Depart Date
             * Format: date
             */
            depart_date: string;
            /** Return Date */
            return_date: string | null;
            /** Price */
            price: string;
            /** Source */
            source: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** DestinationIn */
        DestinationIn: {
            /**
             * Id
             * @description Set for destinations that already belong to the trip.
             */
            id?: number | null;
            /** Name */
            name: string;
            /** Region */
            region?: string | null;
            /** Country */
            country?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Kind */
            kind?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Timezone */
            timezone?: string | null;
            /** Bbox */
            bbox?: number[] | null;
            /** Geoapify Place Id */
            geoapify_place_id?: string | null;
        };
        /** DestinationOut */
        DestinationOut: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Name */
            name: string;
            /** Region */
            region: string | null;
            /** Country */
            country: string | null;
            /** Country Code */
            country_code: string | null;
            /** Kind */
            kind: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Timezone */
            timezone: string | null;
            /** Bbox */
            bbox: number[] | null;
            /** Summary */
            summary: string | null;
            /** Wiki Url */
            wiki_url: string | null;
            /** Image Url */
            image_url: string | null;
            /** Image File */
            image_file: string | null;
            /**
             * Info Status
             * @enum {string}
             */
            info_status: "pending" | "ready" | "not_found" | "failed" | "skipped";
        };
        /**
         * DestinationSuggestion
         * @description A place a trip can go, as found by Geoapify.
         */
        DestinationSuggestion: {
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Region */
            region: string | null;
            /** Country */
            country: string | null;
            /** Country Code */
            country_code: string | null;
            /** Kind */
            kind: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Timezone */
            timezone: string | null;
            /** Bbox */
            bbox: number[] | null;
            /** Geoapify Place Id */
            geoapify_place_id: string | null;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Msg */
            msg: string;
        };
        /** FinishIn */
        FinishIn: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "partial" | "failed";
            /** Summary */
            summary: string;
            /** Sources Checked */
            sources_checked?: string[];
            /** Issues */
            issues?: string[];
        };
        /** GoogleHistoryPoint */
        GoogleHistoryPoint: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Price */
            price: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            worker: components["schemas"]["WorkerStatus"];
        };
        /** HistoryPoint */
        HistoryPoint: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Source */
            source: string;
            /** Price */
            price: string;
        };
        /**
         * IntegrationStatus
         * @description Which API keys are configured. Values are never exposed, only presence.
         */
        IntegrationStatus: {
            /** Geoapify */
            geoapify: boolean;
            /** Serpapi */
            serpapi: boolean;
            /** Travelpayouts */
            travelpayouts: boolean;
            /** Wikimedia */
            wikimedia: boolean;
            /** Agent Api */
            agent_api: boolean;
        };
        /** LoginIn */
        LoginIn: {
            /** Passcode */
            passcode: string;
        };
        /** NearbyAirport */
        NearbyAirport: {
            /** Iata */
            iata: string;
            /** Name */
            name: string;
            /** City */
            city: string | null;
            /** Country Code */
            country_code: string;
            /** Kind */
            kind: string;
            /** Distance Km */
            distance_km: number;
        };
        /** NoteIn */
        NoteIn: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Urls */
            urls?: string[];
        };
        /** NoteOut */
        NoteOut: {
            /** Id */
            id: number;
            /** Trip Id */
            trip_id: number;
            /** Run Id */
            run_id: string | null;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Urls */
            urls: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PersonIn */
        PersonIn: {
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Home Airports */
            home_airports?: string[];
        };
        /** PersonOut */
        PersonOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Home Airports */
            home_airports: string[];
        };
        /** QuoteBatchIn */
        QuoteBatchIn: {
            /** Quotes */
            quotes: {
                [key: string]: unknown;
            }[];
        };
        /** QuoteBatchResult */
        QuoteBatchResult: {
            /** Accepted */
            accepted: components["schemas"]["AcceptedItem"][];
            /** Rejected */
            rejected: components["schemas"]["RejectedItem"][];
            /** Duplicates */
            duplicates: number[];
        };
        /** QuoteOut */
        QuoteOut: {
            /** Id */
            id: number;
            /** Route Id */
            route_id: number;
            /** Source */
            source: string;
            /** Confidence */
            confidence: string;
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /**
             * Depart Date
             * Format: date
             */
            depart_date: string;
            /** Return Date */
            return_date: string | null;
            /** Price Total */
            price_total: string;
            /** Currency */
            currency: string;
            /** Price Home */
            price_home: string | null;
            /** Home Currency */
            home_currency: string;
            /** Passengers */
            passengers: number;
            /** Airlines */
            airlines: string[];
            /** Stops Out */
            stops_out: number | null;
            /** Stops Back */
            stops_back: number | null;
            /** Duration Out Min */
            duration_out_min: number | null;
            /** Duration Back Min */
            duration_back_min: number | null;
            /** Depart At Local */
            depart_at_local: string | null;
            /** Flight Numbers */
            flight_numbers: string[] | null;
            /** Booking Url */
            booking_url: string | null;
            /** Source Url */
            source_url: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Suspect */
            suspect: boolean;
            /** Hidden */
            hidden: boolean;
        };
        /** QuoteUpdate */
        QuoteUpdate: {
            /** Hidden */
            hidden?: boolean | null;
            /** Suspect */
            suspect?: boolean | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Route Ids */
            route_ids?: number[];
        };
        /** RejectedItem */
        RejectedItem: {
            /** Index */
            index: number;
            /** Errors */
            errors: components["schemas"]["FieldError"][];
        };
        /** RejectionOut */
        RejectionOut: {
            /** Id */
            id: number;
            /** Entity */
            entity: string;
            /** Item */
            item: {
                [key: string]: unknown;
            };
            /** Errors */
            errors: components["schemas"]["FieldError"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RouteHistory */
        RouteHistory: {
            /** Currency */
            currency: string;
            /** Points */
            points: components["schemas"]["HistoryPoint"][];
            /** Google */
            google: components["schemas"]["GoogleHistoryPoint"][];
            /** Typical Low */
            typical_low: string | null;
            /** Typical High */
            typical_high: string | null;
            /** Price Level */
            price_level: string | null;
        };
        /** RouteIn */
        RouteIn: {
            /** Label */
            label?: string | null;
            /** Origin Codes */
            origin_codes: string[];
            /** Destination Codes */
            destination_codes: string[];
            /**
             * Trip Type
             * @default round_trip
             * @enum {string}
             */
            trip_type: "round_trip" | "one_way";
            /**
             * Depart From
             * Format: date
             */
            depart_from: string;
            /**
             * Depart To
             * Format: date
             */
            depart_to: string;
            /** Return From */
            return_from?: string | null;
            /** Return To */
            return_to?: string | null;
            /** Min Nights */
            min_nights?: number | null;
            /** Max Nights */
            max_nights?: number | null;
            /**
             * Adults
             * @default 1
             */
            adults: number;
            /**
             * Children
             * @default 0
             */
            children: number;
            /**
             * Cabin
             * @default economy
             * @enum {string}
             */
            cabin: "economy" | "premium_economy" | "business" | "first";
            /** Max Stops */
            max_stops?: number | null;
            /** Sources */
            sources?: ("serpapi" | "travelpayouts" | "agent")[];
            /** Alert Price */
            alert_price?: number | string | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /** RouteOut */
        RouteOut: {
            /** Id */
            id: number;
            /** Trip Id */
            trip_id: number;
            /** Label */
            label: string | null;
            /** Origin Codes */
            origin_codes: string[];
            /** Destination Codes */
            destination_codes: string[];
            /**
             * Trip Type
             * @enum {string}
             */
            trip_type: "round_trip" | "one_way";
            /**
             * Depart From
             * Format: date
             */
            depart_from: string;
            /**
             * Depart To
             * Format: date
             */
            depart_to: string;
            /** Return From */
            return_from: string | null;
            /** Return To */
            return_to: string | null;
            /** Min Nights */
            min_nights: number | null;
            /** Max Nights */
            max_nights: number | null;
            /** Adults */
            adults: number;
            /** Children */
            children: number;
            /**
             * Cabin
             * @enum {string}
             */
            cabin: "economy" | "premium_economy" | "business" | "first";
            /** Max Stops */
            max_stops: number | null;
            /** Sources */
            sources: ("serpapi" | "travelpayouts" | "agent")[];
            /** Alert Price */
            alert_price: string | null;
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RouteSummary
         * @description Per-route status for the Flights page.
         */
        RouteSummary: {
            /** Route Id */
            route_id: number;
            cheapest: components["schemas"]["QuoteOut"] | null;
            /** Last Checked At */
            last_checked_at: string | null;
            /** Quote Count */
            quote_count: number;
        };
        /**
         * RoutineConfig
         * @description Options for agent routines. Price-check (API) routines use none of them.
         */
        RoutineConfig: {
            /** Route Ids */
            route_ids?: number[];
            /** Topic */
            topic?: string | null;
            /** Instructions */
            instructions?: string | null;
            /** Max Turns */
            max_turns?: number | null;
            /** Timeout Min */
            timeout_min?: number | null;
        };
        /** RoutineCreate */
        RoutineCreate: {
            /** Trip Id */
            trip_id: number;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "flight_agent" | "research_agent";
            /** Schedule Cron */
            schedule_cron: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Catch Up
             * @default true
             */
            catch_up: boolean;
            config?: components["schemas"]["RoutineConfig"];
        };
        /** RoutineOut */
        RoutineOut: {
            /** Id */
            id: number;
            /** Trip Id */
            trip_id: number;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "flight_api" | "flight_agent" | "research_agent";
            /** Enabled */
            enabled: boolean;
            /** Schedule Cron */
            schedule_cron: string;
            /** Timezone */
            timezone: string;
            /** Catch Up */
            catch_up: boolean;
            config: components["schemas"]["RoutineConfig"];
            /** Next Run At */
            next_run_at: string | null;
            last_run: components["schemas"]["RunOut"] | null;
        };
        /** RoutineUpdate */
        RoutineUpdate: {
            /** Name */
            name?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Schedule Cron */
            schedule_cron?: string | null;
            /** Catch Up */
            catch_up?: boolean | null;
            config?: components["schemas"]["RoutineConfig"] | null;
        };
        /** RunContext */
        RunContext: {
            /** Run Id */
            run_id: string;
            /** Kind */
            kind: string;
            /**
             * Today
             * Format: date
             */
            today: string;
            /** Trip */
            trip: {
                [key: string]: unknown;
            };
            /** Routes */
            routes: components["schemas"]["ContextRoute"][];
            /** Topic */
            topic: string | null;
            /** Instructions */
            instructions: string | null;
            /** Rules */
            rules: string[];
            /** Blocked Domains */
            blocked_domains: string[];
        };
        /**
         * RunDetailOut
         * @description A run with what it was asked to do and how it was started.
         */
        RunDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Routine Id */
            routine_id: number | null;
            /** Trip Id */
            trip_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "flight_api" | "flight_agent" | "research_agent";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "schedule" | "manual" | "catch_up";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "partial" | "failed" | "timed_out" | "cancelled" | "interrupted";
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Queued At
             * Format: date-time
             */
            queued_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Summary */
            summary: string | null;
            /** Error */
            error: string | null;
            /** Accepted Count */
            accepted_count: number;
            /** Rejected Count */
            rejected_count: number;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Cost Usd Est */
            cost_usd_est: string | null;
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Prompt */
            prompt: string | null;
            /** Argv Redacted */
            argv_redacted: string[] | null;
            /** Exit Code */
            exit_code: number | null;
            /** Report */
            report: {
                [key: string]: unknown;
            } | null;
            /** Log Path */
            log_path: string | null;
        };
        /** RunEventOut */
        RunEventOut: {
            /** Seq */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Type */
            type: string;
            /** Tool Name */
            tool_name: string | null;
            /** Summary */
            summary: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            } | null;
        };
        /** RunOut */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Routine Id */
            routine_id: number | null;
            /** Trip Id */
            trip_id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "flight_api" | "flight_agent" | "research_agent";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "schedule" | "manual" | "catch_up";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "partial" | "failed" | "timed_out" | "cancelled" | "interrupted";
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Queued At
             * Format: date-time
             */
            queued_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Summary */
            summary: string | null;
            /** Error */
            error: string | null;
            /** Accepted Count */
            accepted_count: number;
            /** Rejected Count */
            rejected_count: number;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Cost Usd Est */
            cost_usd_est: string | null;
            /** Cancel Requested */
            cancel_requested: boolean;
        };
        /**
         * RunOutputs
         * @description Everything a run saved or had rejected.
         */
        RunOutputs: {
            /** Quotes */
            quotes: components["schemas"]["QuoteOut"][];
            /** Notes */
            notes: components["schemas"]["NoteOut"][];
            /** Rejections */
            rejections: components["schemas"]["RejectionOut"][];
        };
        /** SerpApiUsage */
        SerpApiUsage: {
            /** Monthly Cap */
            monthly_cap: number;
            /** Used This Month */
            used_this_month: number;
            /** Used Today */
            used_today: number;
            /** Daily Allowance */
            daily_allowance: number;
            /** Remaining Today */
            remaining_today: number;
            /** Plan Searches Left */
            plan_searches_left: number | null;
            /** Account Synced At */
            account_synced_at: string | null;
        };
        /** SessionInfo */
        SessionInfo: {
            /** Authenticated */
            authenticated: boolean;
            /** Local */
            local: boolean;
            /** Passcode Configured */
            passcode_configured: boolean;
        };
        /** SystemStatus */
        SystemStatus: {
            /** Version */
            version: string;
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            worker: components["schemas"]["WorkerStatus"];
            claude: components["schemas"]["ClaudeCliStatus"];
            integrations: components["schemas"]["IntegrationStatus"];
            access: components["schemas"]["AccessInfo"];
        };
        /** TripCover */
        TripCover: {
            /** Image Url */
            image_url: string;
            /** Image File */
            image_file: string | null;
            /** Wiki Url */
            wiki_url: string | null;
            /** Destination Name */
            destination_name: string;
        };
        /** TripIn */
        TripIn: {
            /** Name */
            name: string;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /**
             * Status
             * @default planning
             * @enum {string}
             */
            status: "planning" | "booked" | "done" | "archived";
            /** Home Currency */
            home_currency: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Destinations */
            destinations?: components["schemas"]["DestinationIn"][];
            /** Traveler Ids */
            traveler_ids?: number[];
        };
        /** TripOut */
        TripOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "planning" | "booked" | "done" | "archived";
            /** Home Currency */
            home_currency: string;
            /** Notes */
            notes: string;
            /** Destinations */
            destinations: components["schemas"]["DestinationOut"][];
            /** Travelers */
            travelers: components["schemas"]["PersonOut"][];
            cover: components["schemas"]["TripCover"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkerStatus */
        WorkerStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "stale" | "never_started" | "unknown";
            /** Last Seen */
            last_seen?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    system_status: {
        parameters: {
            query?: {
                recheck?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_people: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"][];
                };
            };
        };
    };
    create_person: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_person: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_person: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trips: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"][];
                };
            };
        };
    };
    create_trip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_destination_info: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_routes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_route: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_route: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_route: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_prices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    best_options: {
        parameters: {
            query?: {
                route_id?: number | null;
                max_age_days?: number;
                limit?: number;
            };
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_summaries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_history: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                route_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    date_grid: {
        parameters: {
            query?: {
                max_age_days?: number;
            };
            header?: never;
            path: {
                route_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DateGridCell"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_quote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs: {
        parameters: {
            query?: {
                trip_id?: number | null;
                routine_id?: number | null;
                kind?: ("flight_api" | "flight_agent" | "research_agent") | null;
                status?: ("queued" | "running" | "succeeded" | "partial" | "failed" | "timed_out" | "cancelled" | "interrupted") | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events: {
        parameters: {
            query?: {
                after_seq?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_outputs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOutputs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_routines: {
        parameters: {
            query?: {
                trip_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_routine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trip_routines: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_routine_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_routine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_routine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_routine_now: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                routine_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trip_notes: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serpapi_usage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerpApiUsage"];
                };
            };
        };
    };
    destination_suggestions: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationSuggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    airports: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    airports_nearby: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                radius_km?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyAirport"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsOut"];
                };
            };
        };
    };
    update_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_context: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_airports: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirportOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_flight_quotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteBatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteBatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_note: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
