/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check for scripts: 200 when the database is reachable, 503 otherwise.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Status
         * @description Setup checklist data: database, worker, Claude CLI, and which API keys are configured.
         */
        get: operations["system_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClaudeCliStatus */
        ClaudeCliStatus: {
            /** Found */
            found: boolean;
            /** Path */
            path?: string | null;
            /** Version */
            version?: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            worker: components["schemas"]["WorkerStatus"];
        };
        /**
         * IntegrationStatus
         * @description Which API keys are configured. Values are never exposed, only presence.
         */
        IntegrationStatus: {
            /** Geoapify */
            geoapify: boolean;
            /** Serpapi */
            serpapi: boolean;
            /** Travelpayouts */
            travelpayouts: boolean;
        };
        /** SystemStatus */
        SystemStatus: {
            /** Version */
            version: string;
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            worker: components["schemas"]["WorkerStatus"];
            claude: components["schemas"]["ClaudeCliStatus"];
            integrations: components["schemas"]["IntegrationStatus"];
            /** Home Currency */
            home_currency: string;
        };
        /** WorkerStatus */
        WorkerStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "stale" | "never_started" | "unknown";
            /** Last Seen */
            last_seen?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    system_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
}
