"""itinerary and places cache

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-26 17:34:43.584268
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "places_cache",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_places_cache")),
    )
    op.create_index(op.f("ix_places_cache_expires_at"), "places_cache", ["expires_at"], unique=False)
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=20), server_default="other", nullable=False),
        sa.Column("status", sa.String(length=12), server_default="idea", nullable=False),
        sa.Column("location_name", sa.String(length=200), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("lat", sa.Double(), nullable=True),
        sa.Column("lon", sa.Double(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("place_provider", sa.String(length=20), nullable=True),
        sa.Column("place_id", sa.Text(), nullable=True),
        sa.Column("place_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "category IN ('sights', 'museum', 'food', 'nature', 'nightlife', 'shopping', 'travel', 'other')",
            name=op.f("ck_activities_valid_category"),
        ),
        sa.CheckConstraint(
            "status IN ('idea', 'planned', 'booked')", name=op.f("ck_activities_valid_status")
        ),
        sa.CheckConstraint("(lat IS NULL) = (lon IS NULL)", name=op.f("ck_activities_lat_lon_pair")),
        sa.CheckConstraint(
            "day IS NOT NULL OR start_time IS NULL", name=op.f("ck_activities_times_need_day")
        ),
        sa.CheckConstraint(
            "start_time IS NOT NULL OR end_time IS NULL", name=op.f("ck_activities_end_needs_start")
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_activities_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_index("ix_activities_trip_day", "activities", ["trip_id", "day"], unique=False)
    op.create_table(
        "itinerary_days",
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=120), server_default="", nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("destination_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["trip_destinations.id"],
            name=op.f("fk_itinerary_days_destination_id_trip_destinations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_itinerary_days_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("trip_id", "day", name=op.f("pk_itinerary_days")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("itinerary_days")
    op.drop_index("ix_activities_trip_day", table_name="activities")
    op.drop_table("activities")
    op.drop_index(op.f("ix_places_cache_expires_at"), table_name="places_cache")
    op.drop_table("places_cache")
    # ### end Alembic commands ###
