"""flights and automation

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 13:59:22.422482
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fx_rates",
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("per_eur", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("currency", name=op.f("pk_fx_rates")),
    )
    op.create_table(
        "flight_routes",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=True),
        sa.Column("origin_codes", postgresql.ARRAY(sa.String(length=3)), nullable=False),
        sa.Column("destination_codes", postgresql.ARRAY(sa.String(length=3)), nullable=False),
        sa.Column("trip_type", sa.String(length=12), server_default="round_trip", nullable=False),
        sa.Column("depart_from", sa.Date(), nullable=False),
        sa.Column("depart_to", sa.Date(), nullable=False),
        sa.Column("return_from", sa.Date(), nullable=True),
        sa.Column("return_to", sa.Date(), nullable=True),
        sa.Column("min_nights", sa.Integer(), nullable=True),
        sa.Column("max_nights", sa.Integer(), nullable=True),
        sa.Column("adults", sa.Integer(), server_default="1", nullable=False),
        sa.Column("children", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cabin", sa.String(length=16), server_default="economy", nullable=False),
        sa.Column("max_stops", sa.Integer(), nullable=True),
        sa.Column(
            "sources",
            postgresql.ARRAY(sa.String(length=20)),
            server_default="{serpapi,travelpayouts}",
            nullable=False,
        ),
        sa.Column("alert_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(trip_type = 'one_way' AND return_from IS NULL AND min_nights IS NULL) OR (trip_type = 'round_trip' AND (return_from IS NULL) <> (min_nights IS NULL))",
            name=op.f("ck_flight_routes_return_rule"),
        ),
        sa.CheckConstraint(
            "cabin IN ('economy', 'premium_economy', 'business', 'first')",
            name=op.f("ck_flight_routes_valid_cabin"),
        ),
        sa.CheckConstraint(
            "trip_type IN ('round_trip', 'one_way')", name=op.f("ck_flight_routes_valid_trip_type")
        ),
        sa.CheckConstraint(
            "(min_nights IS NULL) = (max_nights IS NULL)", name=op.f("ck_flight_routes_nights_pair")
        ),
        sa.CheckConstraint(
            "(return_from IS NULL) = (return_to IS NULL)", name=op.f("ck_flight_routes_return_window_pair")
        ),
        sa.CheckConstraint(
            "adults BETWEEN 1 AND 9 AND children BETWEEN 0 AND 8",
            name=op.f("ck_flight_routes_valid_passengers"),
        ),
        sa.CheckConstraint("depart_to >= depart_from", name=op.f("ck_flight_routes_valid_depart_window")),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_flight_routes_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flight_routes")),
    )
    op.create_index(op.f("ix_flight_routes_trip_id"), "flight_routes", ["trip_id"], unique=False)
    op.create_table(
        "routines",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("schedule_cron", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("catch_up", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("last_slot_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('flight_api', 'flight_agent', 'research_agent')", name=op.f("ck_routines_valid_kind")
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_routines_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routines")),
    )
    op.create_index(op.f("ix_routines_trip_id"), "routines", ["trip_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("routine_id", sa.Integer(), nullable=True),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("trigger", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="queued", nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("argv_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("accepted_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rejected_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd_est", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("log_path", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('flight_api', 'flight_agent', 'research_agent')", name=op.f("ck_runs_valid_kind")
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'partial', 'failed', 'timed_out', 'cancelled', 'interrupted')",
            name=op.f("ck_runs_valid_status"),
        ),
        sa.CheckConstraint(
            "trigger IN ('schedule', 'manual', 'catch_up')", name=op.f("ck_runs_valid_trigger")
        ),
        sa.ForeignKeyConstraint(
            ["routine_id"], ["routines.id"], name=op.f("fk_runs_routine_id_routines"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_runs_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(op.f("ix_runs_routine_id"), "runs", ["routine_id"], unique=False)
    op.create_index("ix_runs_status_queued_at", "runs", ["status", "queued_at"], unique=False)
    op.create_index(op.f("ix_runs_trip_id"), "runs", ["trip_id"], unique=False)
    op.create_table(
        "api_calls",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("endpoint", sa.String(length=60), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("units", sa.Integer(), server_default="1", nullable=False),
        sa.Column("cached", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_api_calls_run_id_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_calls")),
    )
    op.create_index("ix_api_calls_provider_created", "api_calls", ["provider", "created_at"], unique=False)
    op.create_table(
        "flight_quotes",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.String(length=12), nullable=False),
        sa.Column("origin", sa.String(length=3), nullable=False),
        sa.Column("destination", sa.String(length=3), nullable=False),
        sa.Column("depart_date", sa.Date(), nullable=False),
        sa.Column("return_date", sa.Date(), nullable=True),
        sa.Column("price_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price_home", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("home_currency", sa.String(length=3), nullable=False),
        sa.Column("passengers", sa.Integer(), nullable=False),
        sa.Column("airlines", postgresql.ARRAY(sa.String(length=60)), server_default="{}", nullable=False),
        sa.Column("stops_out", sa.Integer(), nullable=True),
        sa.Column("stops_back", sa.Integer(), nullable=True),
        sa.Column("duration_out_min", sa.Integer(), nullable=True),
        sa.Column("duration_back_min", sa.Integer(), nullable=True),
        sa.Column("depart_at_local", sa.String(length=25), nullable=True),
        sa.Column("flight_numbers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("booking_url", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_domain", sa.String(length=120), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("suspect", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("hidden", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("dedupe_key", sa.String(length=64), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "confidence IN ('live', 'cached', 'indicative')", name=op.f("ck_flight_quotes_valid_confidence")
        ),
        sa.CheckConstraint(
            "source IN ('serpapi', 'travelpayouts', 'agent', 'manual')",
            name=op.f("ck_flight_quotes_valid_source"),
        ),
        sa.CheckConstraint("price_total > 0", name=op.f("ck_flight_quotes_positive_price")),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["flight_routes.id"],
            name=op.f("fk_flight_quotes_route_id_flight_routes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_flight_quotes_run_id_runs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_flight_quotes_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flight_quotes")),
    )
    op.create_index(op.f("ix_flight_quotes_dedupe_key"), "flight_quotes", ["dedupe_key"], unique=False)
    op.create_index(
        "ix_flight_quotes_route_dates",
        "flight_quotes",
        ["route_id", "depart_date", "return_date"],
        unique=False,
    )
    op.create_index(
        "ix_flight_quotes_route_observed", "flight_quotes", ["route_id", "observed_at"], unique=False
    )
    op.create_index(op.f("ix_flight_quotes_run_id"), "flight_quotes", ["run_id"], unique=False)
    op.create_index(op.f("ix_flight_quotes_trip_id"), "flight_quotes", ["trip_id"], unique=False)
    op.create_table(
        "route_price_insights",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("depart_date", sa.Date(), nullable=False),
        sa.Column("return_date", sa.Date(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("lowest_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_level", sa.String(length=12), nullable=True),
        sa.Column("typical_low", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("typical_high", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("history", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["flight_routes.id"],
            name=op.f("fk_route_price_insights_route_id_flight_routes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_route_price_insights_run_id_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_price_insights")),
    )
    op.create_index(
        op.f("ix_route_price_insights_route_id"), "route_price_insights", ["route_id"], unique=False
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
        sa.UniqueConstraint("run_id", "seq", name="uq_run_events_run_seq"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_events")
    op.drop_index(op.f("ix_route_price_insights_route_id"), table_name="route_price_insights")
    op.drop_table("route_price_insights")
    op.drop_index(op.f("ix_flight_quotes_trip_id"), table_name="flight_quotes")
    op.drop_index(op.f("ix_flight_quotes_run_id"), table_name="flight_quotes")
    op.drop_index("ix_flight_quotes_route_observed", table_name="flight_quotes")
    op.drop_index("ix_flight_quotes_route_dates", table_name="flight_quotes")
    op.drop_index(op.f("ix_flight_quotes_dedupe_key"), table_name="flight_quotes")
    op.drop_table("flight_quotes")
    op.drop_index("ix_api_calls_provider_created", table_name="api_calls")
    op.drop_table("api_calls")
    op.drop_index(op.f("ix_runs_trip_id"), table_name="runs")
    op.drop_index("ix_runs_status_queued_at", table_name="runs")
    op.drop_index(op.f("ix_runs_routine_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_routines_trip_id"), table_name="routines")
    op.drop_table("routines")
    op.drop_index(op.f("ix_flight_routes_trip_id"), table_name="flight_routes")
    op.drop_table("flight_routes")
    op.drop_table("fx_rates")
    # ### end Alembic commands ###
