"""people trips destinations

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 13:31:36.408108
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "people",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column(
            "home_airports", postgresql.ARRAY(sa.String(length=3)), server_default="{}", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
    )
    op.create_table(
        "trips",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=12), server_default="planning", nullable=False),
        sa.Column("home_currency", sa.String(length=3), nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('planning', 'booked', 'done', 'archived')", name=op.f("ck_trips_valid_status")
        ),
        sa.CheckConstraint(
            "(start_date IS NULL) = (end_date IS NULL) AND (end_date IS NULL OR end_date >= start_date)",
            name=op.f("ck_trips_valid_dates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
    )
    op.create_table(
        "trip_destinations",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("region", sa.String(length=120), nullable=True),
        sa.Column("country", sa.String(length=120), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=True),
        sa.Column("lat", sa.Double(), nullable=False),
        sa.Column("lon", sa.Double(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("bbox", postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column("geoapify_place_id", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("wiki_url", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("image_file", sa.Text(), nullable=True),
        sa.Column("info_status", sa.String(length=12), server_default="pending", nullable=False),
        sa.Column("info_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "info_status IN ('pending', 'ready', 'not_found', 'failed', 'skipped')",
            name=op.f("ck_trip_destinations_valid_info_status"),
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_trip_destinations_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip_destinations")),
    )
    op.create_index(op.f("ix_trip_destinations_trip_id"), "trip_destinations", ["trip_id"], unique=False)
    op.create_table(
        "trip_travelers",
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"], ["people.id"], name=op.f("fk_trip_travelers_person_id_people"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_trip_travelers_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("trip_id", "person_id", name=op.f("pk_trip_travelers")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trip_travelers")
    op.drop_index(op.f("ix_trip_destinations_trip_id"), table_name="trip_destinations")
    op.drop_table("trip_destinations")
    op.drop_table("trips")
    op.drop_table("people")
    # ### end Alembic commands ###
