"""flight choice: the flight picked for a trip, which sets its dates

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-27 00:01:36.920972
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flight_routes", sa.Column("chosen_quote_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        op.f("fk_flight_routes_chosen_quote_id_flight_quotes"),
        "flight_routes",
        "flight_quotes",
        ["chosen_quote_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_flight_routes_chosen_quote_id_flight_quotes"), "flight_routes", type_="foreignkey"
    )
    op.drop_column("flight_routes", "chosen_quote_id")
    # ### end Alembic commands ###
