"""lodging

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-26 18:04:58.321697
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lodging_options",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("url_normalized", sa.Text(), nullable=True),
        sa.Column("site", sa.String(length=60), nullable=True),
        sa.Column("check_in", sa.Date(), nullable=True),
        sa.Column("check_out", sa.Date(), nullable=True),
        sa.Column("guests", sa.Integer(), nullable=True),
        sa.Column("price_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_per_night", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("price_home_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("photos", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("location_name", sa.String(length=300), nullable=True),
        sa.Column("lat", sa.Double(), nullable=True),
        sa.Column("lon", sa.Double(), nullable=True),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("beds", sa.Integer(), nullable=True),
        sa.Column("baths", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("pros", sa.Text(), server_default="", nullable=False),
        sa.Column("cons", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.String(length=12), server_default="candidate", nullable=False),
        sa.Column("favorite", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("added_via", sa.String(length=12), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "added_via IN ('bookmarklet', 'paste', 'serpapi', 'agent', 'manual')",
            name=op.f("ck_lodging_options_valid_source"),
        ),
        sa.CheckConstraint(
            "status IN ('candidate', 'shortlisted', 'booked', 'rejected')",
            name=op.f("ck_lodging_options_valid_status"),
        ),
        sa.CheckConstraint("(lat IS NULL) = (lon IS NULL)", name=op.f("ck_lodging_options_lat_lon_pair")),
        sa.CheckConstraint(
            "check_out IS NULL OR check_in IS NULL OR check_out > check_in",
            name=op.f("ck_lodging_options_valid_dates"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_lodging_options_run_id_runs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_lodging_options_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lodging_options")),
        sa.UniqueConstraint("trip_id", "url_normalized", name="uq_lodging_options_trip_url"),
    )
    op.create_index(op.f("ix_lodging_options_trip_id"), "lodging_options", ["trip_id"], unique=False)
    op.create_table(
        "lodging_votes",
        sa.Column("lodging_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["lodging_id"],
            ["lodging_options.id"],
            name=op.f("fk_lodging_votes_lodging_id_lodging_options"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["people.id"], name=op.f("fk_lodging_votes_person_id_people"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("lodging_id", "person_id", name=op.f("pk_lodging_votes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lodging_votes")
    op.drop_index(op.f("ix_lodging_options_trip_id"), table_name="lodging_options")
    op.drop_table("lodging_options")
    # ### end Alembic commands ###
